### ISSUE TITLE
Need help using WordLand?

### ISSUE THREAD

**Issue by scripting** [scripting/wordlandSupport#15]
This page is linked to from the Support menu item in the WordLand app.

If you have a question about using WordLand this is the place to ask it. 

Also if you think you've found a problem with the software that needs the attention of a developer. 

In either case, be sure to include the following information:

1. What you did.
2. What you expected to happen.
3. What actually happened.

If we can't reproduce the problem we can't help. So try to imagine someone who isn't there with you, who doesn't know what you did, or what you thought the product does.

### Look for error messages

Also -- it's probably a good idea to check for error messages. In Chrome, look in the View menu, Developer sub-menu, JavaScript console command. In other browsers the command is probably somewhere else. You really should look before reporting a problem, and if there is an error message there, include it in your report. 

Don't address your request to me, or anyone else specifically -- because you never know who will have the answer you need. If you address it to someone specific, the others may not feel entitled to respond.

**Comment by xicubed** [comment]
How it started...
<img width="903" alt="Screenshot 2024-12-03 at 11 11 32 AM" src="https://github.com/user-attachments/assets/f4a17636-8832-499b-8feb-e8270b960ebb">
How it's going...
<img width="901" alt="Screenshot 2024-12-03 at 11 12 38 AM" src="https://github.com/user-attachments/assets/89c95702-db26-416e-add9-eb51a9b4ebd0">

I guess I don't understand how to properly add a hyperlink. I tried markdown in Wordland and got markdown in the WordPress post too instead of the hyperlinked "said."

**Comment by scripting** [comment]
What’s your wordpress.com account?

**Comment by xicubed** [comment]
> What’s your wordpress.com account?

 malatmalsfd98527ce7
 
 The post is at https://malatmalsfd98527ce7.wordpress.com/2024/12/03/good-morning-vietnam/

**Comment by scripting** [comment]
1. Please write complete problem reports, and leave out the snark. Not appreciated here. This time I was able to figure out what went wrong from a very incomplete report, but I'm desperately trying to avoid burnout, and will not play 20 Questions. The whole idea of starting with people with development experience is to get great bug reports at the beginning and thus conserve my energy for creative work, not hand-holding for people who are supposed to know what they're doing. 
2. Turn off Markdown mode, and start a new post. 
3. When you want to create a link, copy the URL to the clipboard. Select the text you want to link. Then click the link icon in the popup and paste the URL.

**Comment by scripting** [comment]
BTW, I'm going to take that feature out for now. It needs a better review from me before trying it out with users. ;-)

**Comment by xicubed** [comment]
Oh ok, I didn't get very detailed because I figured it may have a simple answer. It looks like there is, I didn't see the hyperlink creator in the pop-up menu but now I do. I was preoccupied with what that "4" meant in that menu. It looks like the hover text is header type 4. Maybe H<sup>4</sup> would be clearer? I don't see a way to toggle markdown mode or html mode or anything other than what is presented.

I guess in terms of what I expected to see was the editing (bold, etc.) icons in the menu bar vs a pop-up.

Thanks for the comments it helped me see what's going on. This is cool.

**Comment by scripting** [comment]
now it makes sense, i can see that the errant h4 label was distracting. if was able to fix it. 

![image](https://github.com/user-attachments/assets/5588ec6a-430a-4baf-a0df-36f6a37b148f)

**Comment by xicubed** [comment]
I made a nice image of the H4 but forgot to include it...
![Screenshot_2024-12-03_at_1_58_14 PM](https://github.com/user-attachments/assets/a1d2814b-9cba-4171-9ece-cfa0436037a4)

**Comment by scripting** [comment]
Does it work now on your machine?

**Comment by xicubed** [comment]
Yes, everything is working thanks.

**Comment by yudel** [comment]
Possibly relevant to your issue of cutting-and-pasting: Here's a WordPress plugin I use on my WordPress.org site that lets me copy an image to my regular WordPress image library. https://wordpress.org/plugins/the-paste/

**Comment by scripting** [comment]
@geoffoliver -- i just tried this approach in wordland and it worked. the key is turning off those two booleans.

i'm going to test it a bit more before releasing the new version. 

thanks for pushing this. ;-)

**Comment by azizhp** [comment]
Does WordLand share any DNA with Fargo, your earlier outliner project?

As an observation, You seem to have moved away from outlines as a paradigm.

I had experimented with Fargo for posting to my WordPress blog: 

https://www.haibane.info/2013/05/02/using-fargo-for-publishing-to-wordpress-a-great-start-some-rough-edges/

**Comment by scripting** [comment]
@azizhp -- this is not what this space is for.

**Comment by andrewshell** [comment]
**What I Did**

1. In an incognito window (no extensions) Navigate to https://wordland.social/
2. Click "Connect with WordPress.com"
3. See the WordPress login page
4. Login with my email and password
5. Get a code sent to my phone via SMS
6. Enter the verification code and click "Continue"
7. See the WordPress page "Authorize WORDLAND"
8. Click "Approve"
9. See the "You are signed into WordLand, but you are not at this time authorized as a tester." screen.
10. Refresh the page and see the WordLand editor
11. Click "Choose site." but nothing happens**What I Expected**1. After logging in, I'd expect to see the editor without refreshing the page.. After seeing the editor, I'd expect to see my WordPress.com blogs in the "Choose site." menu.

**What Happened**

1. I saw the "not authorized as a tester" screen.
2. I did not see any sites listed when I clicked "Choose site."

**Console Errors**

When I get to the "not authorized as a tester" screen, there are two errors in the console:

"GET https://wordland.social/wordpressuseriswhitelisted?token=<mytoken> 500 (Internal Server Error)"
"GET https://wordland.social/wordpressgetusersites?token=<mytoken> 500 (Internal Server Error)"

In the network tab, both calls show a response of "socket hang up"

Dave, if you want my token, I can email it to you. I figured it best if I didn't share it publicly. :-)

After refreshing the screen there are many errors that look the same as the previous ones but for different paths. All are 500 (Internal Server Error) messages.

<img width="583" alt="Image" src="https://github.com/user-attachments/assets/66c722e6-5a00-4b44-8167-f5dd8ee7ae14" />

**Comment by scripting** [comment]
Andrew I can't check this right away, but you've given me plenty of data. I'm sure it'll be easy to find the problem. Sorry this happened. ;-)

**Comment by scripting** [comment]
Andrew I just saw it crash, I assume that was you (my log doesn't say).

It's crashing as it  loads your site list. 

Not sure what the trouble is and to get to the bottom of it is going to take hours not minutes. 

Just clutching at straws here, it's unusual to use incognito mode, i've never tested it using that, could you try doing it just in an ordinary tab in an ordinary window?

**Comment by scripting** [comment]
one possible way to work around this for now is to create a new wordpress.com account, that doesn't have many sites in it, and thus avoid the site(s) that it's having trouble with.

**Comment by andrewshell** [comment]
This last attempt was not in incognito mode as I was able to determine it didn't seem to help last time. I mostly did it before to make sure there wasn't a conflict with a chrome extension.

**Comment by andrewshell** [comment]
If you have a deleted site in your account it doesn't have a `theSite.options.created_at` value which you're expecting in the convertSite function.  There is also `theSite.is_deleted` boolean you can check to filter out deleted sites.

Here is an example of a deleted site record:

```json
    {
      "ID": 179002210,
      "name": "Demo Market",
      "description": "",
      "URL": "https://demomarket44858034.wordpress.com",
      "jetpack": false,
      "jetpack_connection": false,
      "post_count": 1,
      "subscribers_count": 1,
      "lang": "en",
      "logo": {
        "id": 0,
        "sizes": [],
        "url": ""
      },
      "visible": true,
      "is_private": false,
      "is_coming_soon": false,
      "is_following": true,
      "organization_id": 0,
      "meta": {
        "links": {
          "self": "https://public-api.wordpress.com/rest/v1.1/sites/179002210",
          "help": "https://public-api.wordpress.com/rest/v1.1/sites/179002210/help",
          "posts": "https://public-api.wordpress.com/rest/v1.1/sites/179002210/posts/",
          "comments": "https://public-api.wordpress.com/rest/v1.1/sites/179002210/comments/",
          "xmlrpc": "https://demomarket44858034.wordpress.com/xmlrpc.php"
        }
      },
      "launch_status": "launched",
      "site_migration": null,
      "is_fse_active": false,
      "is_fse_eligible": false,
      "is_core_site_editor_enabled": false,
      "is_wpcom_atomic": false,
      "is_wpcom_staging_site": false,
      "is_deleted": true,
      "is_a4a_client": false,
      "is_a4a_dev_site": false
    }
```

**Comment by scripting** [comment]
@andrewshell -- thanks for the excellent report. 

just made the changes to wpidentity.js and restarted the server.

could you try again, and let's see if the crash is really gone.

the main change was in getUserSites. we now check if the site was deleted, and if so, leave it out of the list of sites.

```
				theSiteList.sites.forEach (function (item) {
					if (!item.is_deleted) { //1/24/25 by DW
						theList.push (convertSite (item));
						}
					});
```

**Comment by drf5n** [comment]
# What I did
1) logged into https://wordland.social/ with Chrome on my Mac
2) authorized and got an edit window
3) edited some text and successfully published to https://drf5n.wordpress.com/2025/02/23/what-is-this-wordland/ 
4) attempted to paste a URL into the edit box with command-V
# What I expected
1) that the text would insert
# What happened
1) the edit box lost focus, and the text did not insert.  
2) I saw the new error console log below.
#What I did next
1) I used the right-button paste command and successfully pasted the url
2) I played around with the editor some more
3) I attempted more command-V pastes, and got more errors. 
# Console Errors

## Error that repeats with each command-V:
<img width="483" alt="Image" src="https://github.com/user-attachments/assets/cdae0c1a-2e0f-4bfb-b814-1ce2cf52ca0b" />

## first errors in Error log:

<img width="621" alt="Image" src="https://github.com/user-attachments/assets/23e457fc-08d8-4d64-9762-9f1e7e092bae" />

**Comment by scripting** [comment]
@drf5n -- thanks for the report and all the detailed info, esp the error reports.

I am testing with Chrome 133.0.6943.98.

Am not seeing the error messages, and am not able to reproduce the problems.

Not sure how to proceed here. One question comes to mind -- does the same thing happen if you paste text that is not a URL? There is special code in the app that processes pasting URLs differently. So that would help to isolate the problem.

Also if anyone tuned in could try to reproduce and see if we can figure out what's going wrong.

Also it could be a plugin that's causing the problem? Try turning them off, see if that changes anything.

**Comment by dlature** [comment]
on my OnePlus Nord N10 phone, the top menu bar is cut off. I've included a screenshot.

![Image](https://github.com/user-attachments/assets/3063f89a-709e-45fc-a876-e8902823a9cd)

**Comment by dlature** [comment]
It seems fixed when I turn the phone sideways and the screen "auto-flips" to Landscape

**Comment by drf5n** [comment]
> Not sure how to proceed here. One question comes to mind -- does the same thing happen if you paste text that is not a URL? There is special code in the app that processes pasting URLs differently. So that would help to isolate the problem.

I turned off all my extensions and restarted Chrome, which removed one of the errors, but I still have a problem on command-V pasting. As before the menu-based pasting works.

The problem happens with both pasting urls and regular text.

The errors in console are:

> code.js?x=2:2242 Uncaught TypeError: Cannot read properties of null (reading 'whichEditor')
    at code.js?x=2:2242:24

<img width="1051" alt="Image" src="https://github.com/user-attachments/assets/5321be5c-78e5-4c39-a592-638bc7f5791f" />

which points towards:

<img width="522" alt="Image" src="https://github.com/user-attachments/assets/6ef3dafe-8b3e-45c2-947f-e3f10c4f5702" />

UI wise, I notice that the focus decoration changes when I hit the command-V.  The blue highlighting around the edit box disappears:

<img width="375" alt="Image" src="https://github.com/user-attachments/assets/d5b87e79-870e-469d-a283-7096272b2b56" />

then, upon command-V, another error shows up in the console log, and the blue disappears:

<img width="465" alt="Image" src="https://github.com/user-attachments/assets/758f4e77-31d3-4323-ba1d-4b63a3dc0bc0" />

If I highlight and command-C to copy a bit of text from the edit box, and I can paste the copied bit back in with the Edit/Paste menu command, the blue border does not disappear.   The Command-V will error and eliminate the blue.

**Comment by BrianPuckett** [comment]
HI,  I encountered difficulty when trying to use WL as a WP "contributor" to post to blog using WP contributor author type.   The action seemed to be the same for two users.   Upon replicating:

WL_Contributor Error

This is a report of when trying to post as WP "Contributor" WL reports "user can not access this private blog" result and failure to post  (no notification of Contributor Post to sender admin portal)

Time afternoon, 4/26

user lyrae.puckett@gmail.com  (contributor)

site: https://mrbrianpuck.wordpress.com, issued INVITATION as author type: 'contributor

Description: User was registered wordpress.com user and was logged into wordpress when executing the wp email with INVITATION link.  User ACCEPTED and APPROVED WordLand access (did not note WP name of approval) WL editor launched and the editor loaded properly. user wrote test message and selected PUBLISH from menu.  the select blog action was replaced with ut upon selecting PUBLISH a POP-UP WL: User can not access this private blog message: 

Let me know if there is anything else I can do to help. And, again  Thank you so much for this great great software.  I am finding a lot of interest from people that want to blog but don't know how.
-brian


Screen shot 

![Image](https://github.com/user-attachments/assets/977a15d1-a73d-4d49-85c2-fdf73c538c17)

Java Console: 
error when trying to post to Mrbrianpuck as contributor

timeline.js
code.js?x=2:2863 startup: WordLand v0.5.6
code.js?x=2:618 hitCounter: msgFromServer == "We got your ping on Sat, 26 Apr 2025 19:07:50 GMT"
api2.js:140 initUserInfo: wordpressMemory.userinfo == {
    "idUser": 264531871,
    "name": "lyraepuckett",
    "username": "lyraepuckett",
    "email": "lyrae.puckett@gmail.com",
    "idPrimaryBlog": 240505901,
    "urlAvatar": "https://0.gravatar.com/avatar/0f0fc2496d186be2b682b211e16213283c729b5dacd94517daa538bfba285146?s=96&d=identicon",
    "urlPrimaryBlog": "http://mrbrianpuck.wordpress.com",
    "urlProfile": "http://gravatar.com/lyraepuckett",
    "whenStarted": "2025-04-09T14:54:39.000Z",
    "ctSites": 1
}
code.js?x=2:278 readPrefs: 0.355 secs
code.js?x=2:2903 startup: 1.144 secs.
/wordpressgetsiteinfo?idsite=243466795&token=cEUpYkNvRXBPJGM4ciVha1ExZyQlak1NMlEwamlKcnhCdDlsISRHT1JlM0Jva003dFlpSGYqMEB5UzVPeGpGWQ:1 
            
            
           Failed to load resource: the server responded with a status of 503 ()Understand this error
/wordpressgetsitecategories?idsite=243466795&token=cEUpYkNvRXBPJGM4ciVha1ExZyQlak1NMlEwamlKcnhCdDlsISRHT1JlM0Jva003dFlpSGYqMEB5UzVPeGpGWQ:1 
            
            
           Failed to load resource: the server responded with a status of 503 ()Understand this error
code.js?x=2:1963 setCatString: err.message == User cannot access this private blog.
code.js?x=2:292 savePrefs: 0.485 secs
api2.js:354 WebSocket connection to 'wss://wordland.social/' failed: Invalid frame header
checkConnection @ api2.js:354Understand this error
api2.js:375 wsConnectToServer: socket received an error.
code.js?x=2:2400 flSimulated == false
code.js?x=2:2435 {
    "title": "",
    "content": "Test 123 welcome to the blog\n\n![](https://puckettchat.wordpress.com/wp-content/uploads/2025/04/image000001.jpeg)",
    "categories": [
        "picture"
    ],
    "idPost": 33,
    "idSite": 243466795,
    "whichEditor": "wizzy",
    "author": {
        "id": 264531871,
        "username": "lyraepuckett",
        "name": "lyraepuckett"
    },
    "whenCreated": "2025-04-11T18:54:16.000Z",
    "flDraftChanged": false,
    "contentType": "markdown",
    "flEnablePublish": true,
    "idDraft": 2433,
    "whenUpdated": "2025-04-11T18:57:12.417Z",
    "url": "https://puckettchat.wordpress.com/2025/04/11/33/",
    "whenPublished": "2025-04-11T18:57:12.107Z"
}
api2.js:354 WebSocket connection to 'wss://wordland.social/' failed: Invalid frame header
checkConnection @ api2.js:354Understand this error
api2.js:375 wsConnectToServer: socket received an error.
api2.js:354 WebSocket connection to 'wss://wordland.social/' failed: Invalid frame header
checkConnection @ api2.js:354Understand this error
api2.js:375 wsConnectToServer: socket received an error.
api2.js:354 WebSocket connection to 'wss://wordland.social/' failed: Invalid frame header
checkConnection @ api2.js:354Understand this error
api2.js:375 wsConnectToServer: socket received an error.
api2.js:354 WebSocket connection to 'wss://wordland.social/' failed: Invalid frame header
checkConnection @ api2.js:354Understand this error
api2.js:375 wsConnectToServer: socket received an error.
api2.js:354 WebSocket connection to 'wss://wordland.social/' failed: Invalid frame header
checkConnection @ api2.js:354Understand this error
api2.js:375 wsConnectToServer: socket received an error.
api2.js:354 WebSocket connection to 'wss://wordland.social/' failed: Invalid frame header
checkConnection @ api2.js:354Understand this error
api2.js:375 wsConnectToServer: socket received an error.
api2.js:354 WebSocket connection to 'wss://wordland.social/' failed: Invalid frame header
checkConnection @ api2.js:354Understand this error
api2.js:375 wsConnectToServer: socket received an error.
code.js?x=2:942 saveDraft: 90 chars, 0.327 secs.
api2.js:354 WebSocket connection to 'wss://wordland.social/' failed: Invalid frame header
checkConnection @ api2.js:354Understand this error
api2.js:375 wsConnectToServer: socket received an error.
api2.js:354 WebSocket connection to 'wss://wordland.social/' failed: Invalid frame header
checkConnection @ api2.js:354Understand this error
api2.js:375 wsConnectToServer: socket received an error.
api2.js:354 WebSocket connection to 'wss://wordland.social/' failed: Invalid frame header
checkConnection @ api2.js:354Understand this error
api2.js:375 wsConnectToServer: socket received an error.
code.js?x=2:942 saveDraft: 103 chars, 0.396 secs.
api2.js:354 WebSocket connection to 'wss://wordland.social/' failed: Invalid frame header
checkConnection @ api2.js:354Understand this error
api2.js:375 wsConnectToServer: socket received an error.
api2.js:354 WebSocket connection to 'wss://wordland.social/' failed: Invalid frame header
checkConnection @ api2.js:354Understand this error
api2.js:375 wsConnectToServer: socket received an error.
api2.js:354 WebSocket connection to 'wss://wordland.social/' failed: Invalid frame header

**Comment by BrianPuckett** [comment]
I am looking at the java console error and I see:
"whenCreated": "2025-04-11T18:54:16.000Z",
"flDraftChanged": false,
"contentType": "markdown",
"flEnablePublish": true,
"idDraft": 2433,
"whenUpdated": "2025-04-11T18:57:12.417Z",
_"url": "https://puckettchat.wordpress.com/2025/04/11/33/",_
"whenPublished": "2025-04-11T18:57:12.107Z"

FYI: url "puckettchat.wordpress.com" is a private wp.com blog that I setup for my family.  Ther user 'lyraepuckett' was an AUTHOR registered to puckettchat but the 'lyraepuckett' was DELETED  'author' to blog puckettchat prior to the test and acceptance of new INVITE as 'contributor' to blog mrbrianpuck.wordpress.com

**Comment by jeherve** [comment]
@BrianPuckett Users with the "contributor" role are not allowed to publish posts ; they can only create drafts and submit them for review.  While this isn't indicated in the WordLand.social UI yet, when you hit the Publish button as a contributor on a site, the post is saved as a daft and submitted for review. 

On your site, however, that didn't work. The error message you received ("User cannot access this private blog.") indicates that the user, while having received an invitation to become a contributor, did not accept the invite. Since they were not a user on the site yet, they were not able to publish the post.

**Comment by scripting** [comment]
@jeherve -- we will look for this condition and react appropriately.

**Comment by scripting** [comment]
@BrianPuckett -- i am seeing the websocket errors here too, but am pretty sure they are not connected to the other problem. i'm working out a fix with my programming partner Chet G. Peety.

:-)

**Comment by BrianPuckett** [comment]
@jeherve @scripting OK,  so not sure if I should continue my report but just so you have it. 

Yes, @jeherve what you suggested did work!  The blog mrbrianpuck was not selected and so I selected it and it published.

1. I went to my WP admin and saw it in the list of posts as pending!
2. I am new to WP this is first time I've gotten contributor.
3. Like an idiot instead of finishing the process in wp admin to post it.  I went back to WL under lyraepuckett and posted again. to see if a second post would come in so I could see what notification I would get in the WP Admin mobule. Unfortunately, it seemed to overwrite the previous test post (but I could as WP admin post successfully the second text post).
5. Then I went back to lyraepuckett account and logged out of both WP and WL.
6. I then used the Wordland.Social url to login to both WP and WL
7. I then tried to post.  I am sorry but not sure of the WL popup and I could not capture it in time and I was not successful in the post and the new test post did not appear in Admin as post pending.
8. 
I did capture the java console below.  I am sorry I could not get screen captures for each step.  Mucho thanks!  Just loving WL. Let the freedom blogs bloom  -brian

timeline.js
code.js?x=2:2863 startup: WordLand v0.5.6
code.js?x=2:618 hitCounter: msgFromServer == "We got your ping on Sun, 27 Apr 2025 21:10:53 GMT"
api2.js:140 initUserInfo: wordpressMemory.userinfo == {
    "idUser": 264531871,
    "name": "lyraepuckett",
    "username": "lyraepuckett",
    "email": "[lyrae.puckett@gmail.com](mailto:lyrae.puckett@gmail.com)",
    "idPrimaryBlog": 240505901,
    "urlAvatar": "https://0.gravatar.com/avatar/0f0fc2496d186be2b682b211e16213283c729b5dacd94517daa538bfba285146?s=96&d=identicon",
    "urlPrimaryBlog": "http://mrbrianpuck.wordpress.com/",
    "urlProfile": "http://gravatar.com/lyraepuckett",
    "whenStarted": "2025-04-09T14:54:39.000Z",
    "ctSites": 1
}
code.js?x=2:278 readPrefs: 0.373 secs
code.js?x=2:2903 startup: 1.111 secs.
code.js?x=2:292 savePrefs: 0.52 secs
code.js?x=2:2400 flSimulated == false
code.js?x=2:2435 {
    "title": "Test 4 of contributor",
    "content": "Test4 of contributor  to mr brian",
    "categories": [],
    "idPost": 788,
    "idSite": 240505901,
    "whichEditor": "wizzy",
    "author": {
        "id": 264531871,
        "username": "lyraepuckett",
        "name": "lyraepuckett"
    },
    "whenCreated": "2025-04-27T20:51:39.000Z",
    "flDraftChanged": false,
    "url": "https://mrbrianpuck.wordpress.com/?p=788",
    "contentType": "markdown",
    "flEnablePublish": true,
    "idDraft": 2812,
    "whenUpdated": "2025-04-27T21:05:21.624Z",
    "whenPublished": "2025-04-27T20:59:57.669Z"
}
code.js?x=2:942 saveDraft: 33 chars, 0.349 secs.
code.js?x=2:942 saveDraft: 33 chars, 0.373 secs.
code.js?x=2:942 saveDraft: 33 chars, 0.372 secs.
code.js?x=2:942 saveDraft: 33 chars, 0.322 secs.
code.js?x=2:942 saveDraft: 33 chars, 0.376 secs.
code.js?x=2:2400 flSimulated == false
code.js?x=2:2435 {
    "title": "Test after restart of WL",
    "content": "Test4 of contributor  to mr brian",
    "categories": [],
    "idPost": 788,
    "idSite": 240505901,
    "whichEditor": "wizzy",
    "author": {
        "id": 264531871,
        "username": "lyraepuckett",
        "name": "lyraepuckett"
    },
    "whenCreated": "2025-04-27T20:51:39.000Z",
    "flDraftChanged": false,
    "url": "https://mrbrianpuck.wordpress.com/?p=788",
    "contentType": "markdown",
    "flEnablePublish": true,
    "idDraft": "2812",
    "whenUpdated": "2025-04-27T21:11:19.111Z",
    "whenPublished": "2025-04-27T20:59:57.669Z"
}
code.js?x=2:942 saveDraft: 2 chars, 0.334 secs.
code.js?x=2:942 saveDraft: 25 chars, 0.319 secs.
code.js?x=2:942 saveDraft: 25 chars, 0.367 secs.
code.js?x=2:1403 publishCommand
/wordpressupdatepost?idsite=240505901&idpost=788&token=cEUpYkNvRXBPJGM4ciVha1ExZyQlak1NMlEwamlKcnhCdDlsISRHT1JlM0Jva003dFlpSGYqMEB5UzVPeGpGWQ:1
           
           
           Failed to load resource: the server responded with a status of 503 ()Understand this error

**Comment by scripting** [comment]
@jeherve -- this is the code that it's calling.

https://github.com/scripting/wpIdentity/blob/main/wpidentity.js#L693

From there it should be clear what message we're sending to wordpress.

**Comment by jeherve** [comment]
> I was not successful in the post and the new test post did not appear in Admin as post pending. The WL Editor did have mrbrianpuck as the blog in the bottom left status menu

Weirdly enough the response you posted shows the post was properly saved on the site. It seems to have worked. It may be worth trying with a new post to ensure things are now working properly.

**Comment by BrianPuckett** [comment]
@jeherve thank you!  I will try again and let you know how it goes later this morning.

**Comment by scripting** [comment]
@BrianPuckett -- the websocket errors you were seeing yesterday should be gone now.

**Comment by scripting** [comment]
Also there was a crashing bug fixed this morning that may have been related to some of the problems you were seeing. There was a problem dealing with sites that weren't hosted on wordpress.com. There's a new thread for that fix.

https://github.com/scripting/wordlandSupport/issues/78

**Comment by BrianPuckett** [comment]
@jeherve @scripting  I am still seeing the same behaviour.

1.  Did test and got error hour ago  then got note things fixed.
2.  Retested but got same behavour

user return popup menu  "user cannot edit post"

java_console


timeline.js
code.js?x=2:2863 startup: WordLand v0.5.6
code.js?x=2:618 hitCounter: msgFromServer == "We got your ping on Mon, 28 Apr 2025 16:20:47 GMT"
api2.js:140 initUserInfo: wordpressMemory.userinfo == {
    "idUser": 264531871,
    "name": "lyraepuckett",
    "username": "lyraepuckett",
    "email": "[lyrae.puckett@gmail.com](mailto:lyrae.puckett@gmail.com)",
    "idPrimaryBlog": 240505901,
    "urlAvatar": "https://0.gravatar.com/avatar/0f0fc2496d186be2b682b211e16213283c729b5dacd94517daa538bfba285146?s=96&d=identicon",
    "urlPrimaryBlog": "http://mrbrianpuck.wordpress.com/",
    "urlProfile": "http://gravatar.com/lyraepuckett",
    "whenStarted": "2025-04-09T14:54:39.000Z",
    "ctSites": 1
}
code.js?x=2:278 readPrefs: 0.348 secs
code.js?x=2:2903 startup: 1.127 secs.
code.js?x=2:292 savePrefs: 0.562 secs
code.js?x=2:942 saveDraft: 72 chars, 0.381 secs.
code.js?x=2:942 saveDraft: 72 chars, 0.394 secs.
code.js?x=2:942 saveDraft: 72 chars, 0.361 secs.
code.js?x=2:2400 flSimulated == false
code.js?x=2:2435 {
    "title": "4/28 after msg a ok test",
    "content": "Test after restart or WL 12 , retry 1, after wp logout and restart wp/wl",
    "categories": [],
    "idPost": 788,
    "idSite": 240505901,
    "whichEditor": "wizzy",
    "author": {
        "id": 264531871,
        "username": "lyraepuckett",
        "name": "lyraepuckett"
    },
    "whenCreated": "2025-04-27T20:51:39.000Z",
    "flDraftChanged": false,
    "url": "https://mrbrianpuck.wordpress.com/?p=788",
    "contentType": "markdown",
    "flEnablePublish": true,
    "idDraft": "2812",
    "whenUpdated": "2025-04-28T16:21:06.105Z",
    "whenPublished": "2025-04-27T20:59:57.669Z"
}
code.js?x=2:942 saveDraft: 72 chars, 0.325 secs.
code.js?x=2:942 saveDraft: 15 chars, 0.4 secs.
code.js?x=2:942 saveDraft: 21 chars, 0.335 secs.
code.js?x=2:942 saveDraft: 29 chars, 0.356 secs.
code.js?x=2:942 saveDraft: 33 chars, 0.349 secs.
code.js?x=2:942 saveDraft: 33 chars, 0.375 secs.
code.js?x=2:1403 publishCommand
/wordpressupdatepost?idsite=240505901&idpost=788&token=cEUpYkNvRXBPJGM4ciVha1ExZyQlak1NMlEwamlKcnhCdDlsISRHT1JlM0Jva003dFlpSGYqMEB5UzVPeGpGWQ:1
           
           
           Failed to load resource: the server responded with a status of 503 ()Understand this error

**Comment by scripting** [comment]
I'm not clear on what the problem is.

What I need is steps to reproduce. 

Or @jeherve -- do you understand what the problem is and is there something WL should do differently?

Just playing back the log doesn't help me get the picture.

**Comment by BrianPuckett** [comment]
@jeherve @scripting 

I am trying to have user lyraepuckett post to mrbrianpuck.wordpress.com blo by issuing a Contributor Invitation by email via WP. 

Let me share what I just did after dave ask about user steps . . .

1,  I logged out of lyraepuckett WP/WL and logged back in at WordLand.Social
2.  WL lloaded properly.
3.   I select the blog to publish Mr. Brian from list
4.  I composed post and published
5.  POST WAS successful.
6. Confirmed in MrBrian Admin as pending.
7. Published post of 1:03 today https://mrbrianpuck.wordpress.com/2025/04/28/4-28-103-pm-test/
8. Went back to WORDLAND for user lyraepuckett.
9. Created new post and selected PUBLISH
10. Menu User cannot edit 
11.   Java console below

I tried to repeat logging fully out of Wordpress and Wordland and can not get a Contributor post to go from user: lyraepuckett to mrbrianpuck blog.   



timeline.js
code.js?x=2:2863 startup: WordLand v0.5.6
code.js?x=2:618 hitCounter: msgFromServer == "We got your ping on Mon, 28 Apr 2025 17:02:57 GMT"
api2.js:140 initUserInfo: wordpressMemory.userinfo == {
    "idUser": 264531871,
    "name": "lyraepuckett",
    "username": "lyraepuckett",
    "email": "[lyrae.puckett@gmail.com](mailto:lyrae.puckett@gmail.com)",
    "idPrimaryBlog": 240505901,
    "urlAvatar": "https://0.gravatar.com/avatar/0f0fc2496d186be2b682b211e16213283c729b5dacd94517daa538bfba285146?s=96&d=identicon",
    "urlPrimaryBlog": "http://mrbrianpuck.wordpress.com/",
    "urlProfile": "http://gravatar.com/lyraepuckett",
    "whenStarted": "2025-04-09T14:54:39.000Z",
    "ctSites": 1
}
code.js?x=2:278 readPrefs: 0.347 secs
code.js?x=2:2903 startup: 1.12 secs.
code.js?x=2:292 savePrefs: 0.49 secs
code.js?x=2:2267 newDraft
code.js?x=2:292 savePrefs: 0.538 secs
dialogs.js?x=0:547 chooseSiteDialog
code.js?x=2:1933 on updateIdSite
10/#:1 Uncaught (in promise) Error: A listener indicated an asynchronous response by returning true, but the message channel closed before a response was receivedUnderstand this error
code.js?x=2:292 savePrefs: 0.488 secs
code.js?x=2:942 saveDraft: 11 chars, 0.335 secs.
code.js?x=2:292 savePrefs: 0.546 secs
code.js?x=2:942 saveDraft: 11 chars, 0.326 secs.
code.js?x=2:942 saveDraft: 11 chars, 0.389 secs.
code.js?x=2:942 saveDraft: 11 chars, 0.351 secs.
code.js?x=2:942 saveDraft: 11 chars, 0.425 secs.
code.js?x=2:2400 flSimulated == false
code.js?x=2:2435 {
    "title": "4/28  1\"03 pm  test",
    "content": "<p><br></p>",
    "categories": [],
    "idSite": 240505901,
    "whichEditor": "wizzy",
    "author": {
        "id": 264531871,
        "username": "lyraepuckett",
        "name": "lyraepuckett"
    },
    "whenCreated": "2025-04-28T17:03:30.929Z",
    "flDraftChanged": false,
    "url": "https://mrbrianpuck.wordpress.com/",
    "flEnablePublish": true,
    "idDraft": "2828",
    "whenUpdated": "2025-04-28T17:03:44.978Z"
}
code.js?x=2:942 saveDraft: 4 chars, 0.335 secs.
code.js?x=2:415 viewUserInfo: theUserInfo == {
    "idUser": 264531871,
    "name": "lyraepuckett",
    "username": "lyraepuckett",
    "email": "[lyrae.puckett@gmail.com](mailto:lyrae.puckett@gmail.com)",
    "idPrimaryBlog": 240505901,
    "urlAvatar": "https://0.gravatar.com/avatar/0f0fc2496d186be2b682b211e16213283c729b5dacd94517daa538bfba285146?s=96&d=identicon",
    "urlPrimaryBlog": "http://mrbrianpuck.wordpress.com/",
    "urlProfile": "http://gravatar.com/lyraepuckett",
    "whenStarted": "2025-04-09T14:54:39.000Z",
    "ctSites": 1
}
code.js?x=2:1403 publishCommand
code.js?x=2:942 saveDraft: 4 chars, 0.338 secs.
code.js?x=2:1210 saveFeed: idsite == 240505901
code.js?x=2:1295 saveFeed: data.urlPublic == https://wordland.social/lyraepuckett/240505901/rss.xml
buildrss.js:15 rssCloudPing: urlServer == https://rpc.rsscloud.io/ping, urlFeed == https://wordland.social/lyraepuckett/240505901/rss.xml, status == success
code.js?x=2:292 savePrefs: 0.54 secs
code.js?x=2:942 saveDraft: 4 chars, 0.443 secs.
code.js?x=2:942 saveDraft: 4 chars, 0.353 secs.
code.js?x=2:942 saveDraft: 4 chars, 0.416 secs.
code.js?x=2:942 saveDraft: 4 chars, 0.341 secs.
code.js?x=2:2400 flSimulated == false
code.js?x=2:2435 {
    "title": "4/28  1:06 pm  second  test",
    "content": "test",
    "categories": [],
    "idPost": 806,
    "idSite": 240505901,
    "whichEditor": "wizzy",
    "author": {
        "id": 264531871,
        "username": "lyraepuckett",
        "name": "lyraepuckett"
    },
    "whenCreated": "2025-04-28T17:04:07.000Z",
    "flDraftChanged": false,
    "url": "https://mrbrianpuck.wordpress.com/?p=806",
    "flEnablePublish": true,
    "idDraft": "2828",
    "whenUpdated": "2025-04-28T17:06:36.961Z",
    "contentType": "markdown",
    "whenPublished": "2025-04-28T17:04:09.062Z"
}
code.js?x=2:942 saveDraft: 6 chars, 0.384 secs.
code.js?x=2:942 saveDraft: 19 chars, 0.373 secs.
code.js?x=2:942 saveDraft: 24 chars, 0.372 secs.
code.js?x=2:942 saveDraft: 24 chars, 0.41 secs.
code.js?x=2:1403 publishCommand
/wordpressupdatepost?idsite=240505901&idpost=806&token=cEUpYkNvRXBPJGM4ciVha1ExZyQlak1NMlEwamlKcnhCdDlsISRHT1JlM0Jva003dFlpSGYqMEB5UzVPeGpGWQ:1
           
           
           Failed to load resource: the server responded with a status of 503 ()Understand this error

**Comment by jeherve** [comment]
I believe I understand the issue.

WordPress' `contributor` role is not allowed to publish posts, or to edit posts that have already been published. Contributors can only write drafts, save drafts, and submit drafts for reviews.

@BrianPuckett Your `lyraepuckett` contributor user is currently trying to edit a post that's already published. That's not something you can do.
The immediate workaround, if you wanted that user to be able to edit their own posts even once they've been published, would be to change their role to `author` instead of `contributor`.

@scripting I believe there may be room for improvement in WordLand to better support contributors:

**Update the default UI when a user's role is `contributor`**

This Publish button should say "submit for review".

<img width="376" alt="Image" src="https://github.com/user-attachments/assets/1ba56983-08c1-4829-97d0-f05f3ff72223" />

In practice, when you make your `getUserSites` call in `wpIdentity`, each site in the response will include a `capabilities` object. Contributors have the `edit_posts` capability, but not the `publish_posts` capability.

**Do not load a post in the editor when it's already been published and the user has the `contributor` role.**

- In `wordpressgetrecentuserdrafts`, since contributors cannot edit published posts, let's not return published posts in the editor.

**Comment by BrianPuckett** [comment]
@jeherve yes thank you that's it,  trying to get ppl to author but 1) ppl scared to post live, b) contrib. allows review which seems like be good thing as try to grow communities around handsoff.  https//handsoffleesburg.wordpress.com and for 5/1 May Day Strong  2nd, https://handsoffclarke.wordpress.com. let the freedom blogs bloom  --thanks so much  -brian

**Comment by scripting** [comment]
@BrianPuckett --

Jeremy has given me the information I need, it'll probably be a few days before I can work on it, so hopefully he's given you a way to work around the problem for now. 

It's important that when the new version is available, you try it, and tell us whether it fixes the problem.

**Comment by BrianPuckett** [comment]
@scripting thank you! @jeherve has been very helpful and I am all set.  No rush.   I will definitely be able to test when you are ready. Thank you!

**Comment by fmcpherson** [comment]
Trying to use the new linkblog bookmarklet after following the instructions to add it to the Chrome bookmark bar. 

What I Am Doing
1. Using Google Chrome on my Macbook
2. Go to a web site: https://9to5google.com/2025/07/03/samsungs-galaxy-z-fold-7-looks-slim-and-sleek-in-first-hands-on-leak/
3. Click the Linkblog item on the bookmark bar

What Happens
1. New tab opens in Chrome
2. The Wordland.social site starts to open
3. A dialog appears: "Create a new linkblog post?" I click yes
4. Wordland finishes loading

What I expect
As per the description of the page a new entry (post) should be in the Wordland edit box with the title of the source page and a link. 

What Is Happening
The previous blog post entry that I wrote appears. The new post with the expected page title does not appear. 

Note that previous to doing the above I loaded Wordland.social and provided the default linkblog site and categories using the tools menu.

**Comment by scripting** [comment]
@fmcpherson -- thanks for the report. i was able to reproduce the problem, found a bug, fixed it resulting in v0.5.18.

try again. ;-)

**Comment by fmcpherson** [comment]
Post now succeeded as expected. Another piece of feedback. When Wordland loads with the title of the source page in the edit box the publish/update button is grayed out. I just clicked it and it worked but I think it should be dark.

**Comment by fmcpherson** [comment]
I've created a new Wordpress site to host my linkblog and I expect the posts to include the source page title and a link to that page. 

What I Am Doing

1. Using Google Chrome on my Macbook
2. Go to a web site: https://9to5google.com/2025/07/03/samsungs-galaxy-z-fold-7-looks-slim-and-sleek-in-first-hands-on-leak/
3. Click the Linkblog item on the bookmark bar

What Happens

1. New tab opens in Chrome
2. The Wordland.social site starts to open
3. A dialog appears: "Create a new linkblog post?" I click yes
4. Wordland finishes loading

What I expect

The title of the source page should appear in the edit box followed by the source domain that is a hyperlink to the source page. When published both the title and the link should appear on the Wordpress site.

What is happening

The title of the source page appears but the domain and link is not being added. See this: https://fjmnotes6.wordpress.com/2025/07/03/9/ compared to this: https://linkblog3.wordpress.com/2025/07/01/8515/. The link is also not being added to the description in the RSS feed, see: https://wordland.social/fjmnotes/246129403/rss.xml

**Comment by scripting** [comment]
@fmcpherson -- it doesn't work that way. explained in great detail in the change note, with links.

net-net -- i want the linkblog functionality for the reader i'm doing, and right now there is no idea of what a linkblog is. it's very unlikely your feed reader will know what to do with it, which is why i disclaimed on my blog that this is probably right now only for me.

**Comment by scripting** [comment]
It's also very unlikely that WordPress will know what to do with it either, but we're working on that. ;-)

**Comment by scripting** [comment]
This place is for reporting bugs and getting help with using the product.

**Comment by dsearls** [comment]
I'm getting an error. Here is a screenshot of the Javascript console under View / Developer:

<img width="1075" height="730" alt="Image" src="https://github.com/user-attachments/assets/b82e3bb2-5e1a-4fc5-8a50-d42cb5327850" />

**Comment by scripting** [comment]
@dsearls -- thanks for the excellent report.

what i see is that wordland tried to get the categories for your site, "Doc Searls Weblog" probably, and was told that 

`API calls to this blog have been disabled`

It looks like the categories were not displayed, but also looks like the software continued.

I would check with the people who run your site, you can probably just send them a link to this comment.

**Comment by dsearls** [comment]
Ah, so that message was from my blog's host. I'll send the link to your comment to my concierge there. Thanks!

**Comment by scripting** [comment]
@dsearls -- checking in to see if the problem was solved, or if we still need to look into what was going wrong. happy to help debug this. ;-)

**Comment by BrianPuckett** [comment]
Hi,  I am having trouble viewing content in FDL and WRDL.  I logged into feedland and every thing loaded properly and I selected MY NEWS to read my feeds with categories displayed but NO DATA, blank view.  I poked around and quicky got a socket error.  (I am sry I did not capture session).  I exited app/wordpress and then 

I logged into WordLand.  There is no edit box for notes or navigation menu (as shown) in

1.  Screen shot of my desktop with menu drop down but no place to edit or select NOTE

I attach also the java console from yesterday from my WordLand login.

Please let me know if there is anything else I can do to assist you in helping me.  TY, Brian 

[wordland no note error java console.txt](https://github.com/user-attachments/files/22173531/wordland.no.note.error.java.console.txt)
![Image](https://github.com/user-attachments/assets/193e63f5-5f19-41f7-8807-3c66302f35db)

[wordland no note error java console.txt](https://github.com/user-attachments/files/22173559/wordland.no.note.error.java.console.txt)

**Comment by scripting** [comment]
WordLand appears to be running fine from here. If you want to report a problem please say exactly what you did. 

There were problems with FeedLand earlier today, but they should be fixed now. I'll put a note on scripting.com shortly about this. 

From the screen shot of WordLand it looks like it didn't connect to the server. The thing to do when that happens is wait a bit and try again.

**Comment by wijai** [comment]
At 2025-11-14  around 8:00 CET I did some usability tests on
wordland. During testing I got an "api calls to this endpoint are
disabled" error message.

This is what happened: I tried out the markdown features in wordland
and that did go fine, details in attached file. I published and
checked the rss feed and that was fine also.

Then I added a description of what I saw in in the feed in the still
open edit window of wordland and hit publish, to be greeted with the
api error.

I checked the wordpress site and got the following information:
"[peauua.wordpress.com](http://peauua.wordpress.com/) is no longer available.
This blog has been archived or suspended in accordance with our Terms
of Service.
For more information and to contact us please read the message in your
dashboard."

The text I posted seems harmless enough, so I assume there is some
technical reason for the suspension.

I asked wordpress for clarification, when I get information I will add it here

[trying-out-wordland.md](https://github.com/user-attachments/files/23547906/trying-out-wordland.md)

**Comment by wijai** [comment]
Previous issue solved. False positive from an automattic anti-spam control. I still do not know what triggered it in the published text, but all is fine now.

**Comment by tipa16384** [comment]
Not an issue _per se_, but I was moving my site _off_ of WordPress onto Hugo for reasons of complete control and I couldn't think of a Markdown editor I liked better than WordLand. Would it be able to be run locally with a localhost-based server standing in for a WordPress host?

**Comment by scripting** [comment]
@tipa16384 -- thanks -- glad you like WordLand. :-)

We're working on a new version, and for now it's all WordPress. 

We may at some point hook it up to other CMS's -- but that's quite a ways off.
